name: Unit Tests

on:
  push:
    branches:
      - tls
    paths:
      - src/tls/*
  workflow_dispatch:

env:
  AUTOTESTER_ROM: ${{github.workspace}}/CE.rom
  LWIP_TESTS: ${{github.workspace}}/tests
  CEMU_PATH: ${{github.workspace}}/CEmu
  HOST_DOMAIN: "https://cagstech.com"
  CEDEV_BIN: ${{github.workspace}}/CEdev/bin

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
        
    steps:
      - name: Checkout TLS branch
        uses: actions/checkout@v4
        with:
          ref: 'tls'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar wget
        
      - name: Download and extract CEdev
        run: |
          curl -sL github.com/CE-Programming/toolchain/releases/download/v11.2/CEdev-Linux.tar.gz | tar xz
          
      - name: Add CEdev to PATH
        run: |
          echo "${{github.workspace}}/CEdev/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH

      - name: Download CEmu Rom
        run: |
          curl -A "Mozilla/5.0" -sL https://cagstech.com/resources/CE.rom -o ${{ env.AUTOTESTER_ROM }}

      - name: Checkout CEmu
        uses: actions/checkout@v3
        with:
          repository: CE-Programming/CEmu
          ref: master
          path: ${{env.CEMU_PATH}}
          persist-credentials: false
          
      - name: Build CEmu
        run: make -j4 -C ${{env.CEMU_PATH}}/core
        
      - name: Build Autotester CLI
        run: make -j4 -C ${{env.CEMU_PATH}}/tests/autotester ${{matrix.ldflags}}
        
      - name: Install Autotester CLI
        run: cmake -E copy ${{env.CEMU_PATH}}/tests/autotester/autotester${{matrix.exe}} ${{env.CEDEV_BIN}}/cemu-autotester${{matrix.exe}}

      - name: Run Unit Tests
        run: |
          find ${{env.LWIP_TESTS}} -name autotest.json -print0 | {
            # Initialize variables
            total_tests=0
            total_passed=0
            total_failed=0

            while read -rd '' test; do
              status=0
              test_dir=$(dirname "$test")
              make -C "$test_dir" clean
              make -C "$test_dir" all test || $((status=$?))
              
              $(( total_tests += 1 ))
              if [ $status -eq 0 ]; then
                $(( total_passed += 1 ))
                test_status="passed"
              else
                $(( total_failed += 1 ))
                test_status="failed"
              fi
              echo -e "TEST name=$test_dir status=$test_status\n" >> ${{github.workspace}}/test_results.log
            done
            echo -e "\nSUMMARY: tests=$total_tests, passed=$total_passed, failed=$total_failed" >> ${{github.workspace}}/test_results.log
          }

      - name: Upload Results Logfile
        uses: actions/upload-artifact@v3
        with:
          name: results.log
          path: ${{github.workspace}}/test_results.log
          
      - name: Remove CEmu Rom
        if: always()
        run: rm ${{env.AUTOTESTER_ROM}}
