name: Unit Tests

on:
  push:
    branches:
      - tls
    paths:
      - src/tls/*
  workflow_dispatch:

env:
  AUTOTESTER_ROM: ${{github.workspace}}/CE.rom
  LWIP_TESTS: ${{github.workspace}}/tests
  CEMU_PATH: ${{github.workspace}}/CEmu
  HOST_DOMAIN: "https://cagstech.com"
  CEDEV_BIN: ${{github.workspace}}/CEdev/bin

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
        include:
        - language: c-cpp
          build-mode: manual
        
    steps:
      - name: Checkout TLS branch
        uses: actions/checkout@v4
        with:
          ref: 'tls'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar wget
        
      - name: Download and extract CEdev
        run: |
          curl -sL github.com/CE-Programming/toolchain/releases/download/v11.2/CEdev-Linux.tar.gz | tar xz
          
      - name: Add CEdev to PATH
        run: |
          echo "${{github.workspace}}/CEdev/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH

      - name: Download CEmu Rom
        run: |
          curl -A "Mozilla/5.0" -sL https://cagstech.com/resources/CE.rom -o ${{ env.AUTOTESTER_ROM }}

      - name: Checkout CEmu
        uses: actions/checkout@v3
        with:
          repository: CE-Programming/CEmu
          ref: master
          path: ${{env.CEMU_PATH}}
          persist-credentials: false
          
      - name: Build CEmu
        run: make -j4 -C ${{env.CEMU_PATH}}/core
        
      - name: Build Autotester CLI
        run: make -j4 -C ${{env.CEMU_PATH}}/tests/autotester ${{matrix.ldflags}}
        
      - name: Install Autotester CLI
        run: cmake -E copy ${{env.CEMU_PATH}}/tests/autotester/autotester${{matrix.exe}} ${{env.CEDEV_BIN}}/cemu-autotester${{matrix.exe}}

      - name: Run Unit Tests
        run: |
          find ${{env.LWIP_TESTS}} -name autotest.json -print0 | {
            declare -A test_results
            test_results[results][summary][tests]=0
            test_results[results][summary][passed]=0
            test_results[results][summary][failed]=0
            while read -d '' test; do
              status=0
              make -C $(dirname $test) clean
              make -C $(dirname $test) all test || $((status = $?))
              declare -A result
              result[name]=$(dirname $test)
              if [ $status -eq 0 ]; then
                $((test_results[results][summary][passed] += 1))
                result[status]="passed"
              else
                $((test_results[results][summary][failed] += 1))
                result[status]="failed"
              fi
              $((test_results[results][summary][tests] += 1))
              test_results[results][tests][] = result
            done
            declare -r JSON_CONTENT=$(jq $test_results)
            echo $JSON_CONTENT
            echo $JSON_CONTENT > ${{github.workspace}}/test_results.json   
          }

      - name: Remove CEmu Rom
        if: always()
        run: rm ${{env.AUTOTESTER_ROM}}
